'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,errorText,type Member} from '@/lib/api';
import {IdentificationCard,Key} from './icons';
export function ProfileEditor({member,onSaved}:{member:Member;onSaved:()=>Promise<void>}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{await api('/me/profile',{display_name:f.get('display_name'),phone:f.get('phone')});await onSaved();setMessage('个人信息已保存');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <section className="panel profile-editor"><header className="member-section-heading"><i><IdentificationCard size={27}/></i><div><span className="eyebrow">EDIT PROFILE</span><h2>修改个人信息</h2></div></header><form className="stack-form" onSubmit={submit}><label><span>登录邮箱</span><input value={member.email} readOnly aria-readonly="true"/><small>用于登录与接收订单交付邮件。</small></label><label><span>昵称 *</span><input name="display_name" required maxLength={40} defaultValue={member.display_name||member.email.split('@')[0]} autoComplete="nickname" placeholder="请输入昵称"/></label><label><span>联系电话（选填）</span><input type="tel" name="phone" maxLength={24} defaultValue={member.phone} autoComplete="tel" placeholder="请输入联系电话"/><small>仅用于联系，不作为登录账号。</small></label>{error?<p role="alert" className="error-message">{error}</p>:null}{message?<p role="status" className="notice">{message}</p>:null}<button className="primary" disabled={busy}>{busy?'保存中…':'保存个人信息'}</button></form></section>;
}
export function PasswordEditor(){const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/me/password',{current_password:f.get('current_password'),new_password:f.get('new_password'),confirmation:f.get('confirmation')});router.replace('/login?password_changed=1');router.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <section className="panel profile-editor"><header className="member-section-heading"><i><Key size={28}/></i><div><span className="eyebrow">ACCOUNT SECURITY</span><h2>修改密码</h2></div></header><form className="stack-form" onSubmit={submit}><label><span>当前密码 *</span><input type="password" name="current_password" required maxLength={128} autoComplete="current-password" placeholder="请输入当前密码"/></label><label><span>新密码 *</span><input type="password" name="new_password" required minLength={8} maxLength={128} autoComplete="new-password" placeholder="请输入至少 8 位的新密码"/></label><label><span>确认新密码 *</span><input type="password" name="confirmation" required minLength={8} maxLength={128} autoComplete="new-password" placeholder="再次输入新密码"/></label><p className="notice">修改成功后，所有设备将退出登录，请使用新密码重新登录。</p>{error?<p role="alert" className="error-message">{error}</p>:null}<button className="primary" disabled={busy}>{busy?'正在修改…':'确认修改密码'}</button></form></section>;}
