'use client';
import {useEffect,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {api,errorText} from '@/lib/api';
type Mode='login'|'register'|'reset';
export default function Auth(){
  const [mode,setMode]=useState<Mode>('login'),[captcha,setCaptcha]=useState<{id:string;image:string}|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sending,setSending]=useState(false),[wait,setWait]=useState(0),[emailId,setEmailId]=useState(''),[account,setAccount]=useState('');
  const params=useSearchParams(),router=useRouter();
  async function refresh(){try{setCaptcha(await api<{id:string;image:string}>('/auth/captcha'));}catch(e){setError(errorText(e));}}
  useEffect(()=>{void refresh();},[]);
  useEffect(()=>{if(wait<=0)return;const t=setTimeout(()=>setWait(w=>w-1),1000);return ()=>clearTimeout(t);},[wait]);
  function change(next:Mode){setMode(next);setError('');setNotice('');setEmailId('');setWait(0);if(next==='login')void refresh();}
  async function send(){setSending(true);setError('');try{const d=await api<{id:string;mock_code?:string;message:string}>('/auth/code',{email:account,purpose:mode});setEmailId(d.id);setWait(60);setNotice(d.mock_code?`演示邮箱验证码：${d.mock_code}（仅本地测试，不发送邮件）`:d.message);}catch(e){setError(errorText(e));}finally{setSending(false);}}
  async function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{if(mode==='reset'&&!emailId)throw new Error('请先获取邮箱验证码');await api(`/auth/${mode}`,{account,password:data.get('password'),confirmation:data.get('confirmation'),...(mode==='register'?{}:{challenge_id:mode==='login'?captcha?.id:emailId,code:data.get('code')})});if(mode==='reset'){change('login');setNotice('密码重置请求已处理，请使用新密码登录');return;}const next=params.get('next');const safe=next&&/^\/(?:account|orders|tickets|products\/\d+|offers\/(?:recharge|newcomer)|lottery)(?:\?.*)?$/.test(next)?next:'/account';router.push(safe);router.refresh();}catch(e){setError(errorText(e));if(mode==='login')void refresh();}finally{setBusy(false);}}
  return <section className="auth-card"><div className="auth-copy"><span className="eyebrow">{mode==='reset'?'PASSWORD RESET':'MEMBER ACCESS'}</span><h1>{mode==='reset'?'找回登录密码':mode==='register'?'注册云充汇':'登录云充汇'}</h1><p>{mode==='reset'?'通过绑定邮箱验证身份，安全重置登录密码。':'登录后可查看购买记录、账单与工单。'}</p></div>{mode!=='reset'?<div className="auth-tabs" role="tablist" aria-label="账号访问"><button role="tab" aria-selected={mode==='login'} className={mode==='login'?'active':''} onClick={()=>change('login')}>登录</button><button role="tab" aria-selected={mode==='register'} className={mode==='register'?'active':''} onClick={()=>change('register')}>注册</button></div>:null}<form className="stack-form auth-stack" onSubmit={submit} key={mode}><label><span>{mode==='login'?'账号':mode==='reset'?'绑定邮箱':'邮箱'}</span><input name="account" type={mode==='login'?'text':'email'} required maxLength={191} autoComplete={mode==='login'?'username':'email'} placeholder={mode==='login'?'用户名 / 手机号 / 邮箱':'请输入常用邮箱'} value={account} onChange={e=>{setAccount(e.target.value);setEmailId('');}}/></label>{mode==='reset'?<label><span>邮箱验证码</span><div className="email-code-row"><input name="code" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" placeholder="输入 6 位验证码"/><button type="button" disabled={sending||wait>0||!account} onClick={send}>{wait>0?`${wait} 秒后重发`:sending?'发送中…':'发送验证码'}</button></div><small>验证码 10 分钟内有效。</small></label>:null}<label><span>{mode==='login'?'密码':mode==='reset'?'设置新密码':'设置密码'}</span><input name="password" type="password" required minLength={8} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='login'?'请输入登录密码':'至少 8 位'}/></label>{mode!=='login'?<label><span>再次输入密码</span><input name="confirmation" type="password" required minLength={8} maxLength={128} autoComplete="new-password" placeholder="必须与上方密码一致"/></label>:<label><span>图形验证码</span><div className="captcha-row"><input name="code" required maxLength={4} autoComplete="one-time-code" placeholder="输入验证码"/><button type="button" onClick={refresh} aria-label="刷新图形验证码" title="点击刷新验证码">{captcha?<img src={captcha.image} alt="图形验证码"/>:'点击加载'}</button></div></label>}{notice?<p role="status" className="notice">{notice}</p>:null}{error?<p role="alert" className="error-message">{error}</p>:null}<button className="primary wide" disabled={busy||(mode==='login'&&!captcha)}>{busy?'处理中…':mode==='login'?'登录':mode==='register'?'注册':'重置密码'}</button><button type="button" className="text-button" onClick={()=>change(mode==='reset'?'login':'reset')}>{mode==='reset'?'返回登录':'忘记密码？'}</button></form></section>;
}
