'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,ApiError,errorText,money,type Product,type Order} from '@/lib/api';
import OrderReceipt,{cacheOrder} from './order-receipt';
type Info={participants:number;probability:number;mock:boolean};
type Result={won:boolean;already_entered:boolean;variant_id:string;order_id:string|null};
export default function ProductLottery({product:p}:{product:Product}){
  const [variantId,setVariantId]=useState(p.variants.find(v=>v.stock>0)?.id||p.variants[0]?.id||''),[info,setInfo]=useState<Info|null>(null),[result,setResult]=useState<Result|null>(null),[order,setOrder]=useState<Order|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[login,setLogin]=useState(false);
  const variant=p.variants.find(v=>v.id===variantId);
  useEffect(function loadActivity(){let active=true;api<Info>(`/products/${p.id}/lottery`).then(d=>{if(active)setInfo(d);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[p.id]);
  async function enter(){setBusy(true);setError('');setLogin(false);try{const r=await api<Result>(`/products/${p.id}/lottery`,{variant_id:variantId});setResult(r);if(r.order_id){cacheOrder(r.order_id);setOrder(await api<Order>(`/orders/${r.order_id}/status`));}}catch(e){setError(errorText(e));if(e instanceof ApiError&&e.status===401)setLogin(true);}finally{setBusy(false);}}
  if(order)return <><p className="notice">{result?.already_entered?'这是你今天已保存的中奖结果，未重复扣库存或发货。':'恭喜中奖！已免费发放所选规格的商品。'}</p><OrderReceipt initial={order}/></>;
  return <section className="panel lottery-view"><span className="eyebrow">FREE PRODUCT GIVEAWAY</span><div className="lottery-prize"><img src={p.image} alt={p.name} width={90} height={90}/><h1>{p.name}</h1><div className="product-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><p>免费参与，中奖直接发放所选规格的商品。</p></div><p className="notice">演示抽奖 · 无需购买或充值 · 中奖后生成零元订单和演示交付内容</p><fieldset className="checkout-fieldset"><legend>选择奖品规格</legend><div className="variant-options">{p.variants.map(v=><label key={v.id} className={`variant-option ${variantId===v.id?'selected':''}`}><input type="radio" name="lottery-variant" checked={variantId===v.id} disabled={!v.stock||busy||!!result} onChange={()=>setVariantId(v.id)}/><span><b>{v.name}</b><small>价值 {money(v.price)} · 库存 {v.stock}</small></span></label>)}</div></fieldset><div className="summary-line"><span>本期参与人数</span><strong>{info?.participants??'—'} 人</strong></div><div className="summary-line"><span>中奖概率</span><strong>{info?`${info.probability*100}%`:'—'}</strong></div><p>每个账号每件商品每日一次（UTC 日界线），所有规格共享次数。中奖后扣减 1 件规格库存，结果和订单在账号中保存。优惠券不用于免费抽奖。</p>{error?<p className="error-message" role="alert">{error}</p>:null}{login?<Link className="primary" href={`/login?next=${encodeURIComponent(`/products/${p.id}`)}`}>登录后参与</Link>:null}{result?<div className="lottery-result"><h2>{result.won?'恭喜中奖！':'本次未中奖，明天再来试试'}</h2>{result.already_entered?<p>你今天已经参与，这是已保存的结果。</p>:null}{result.order_id?<Link className="primary" href={`/orders?tab=mine&order=${encodeURIComponent(result.order_id)}`}>查看中奖订单</Link>:<Link className="secondary" href="/">返回商品中心</Link>}</div>:<button className="primary wide" disabled={busy||!info||!info.mock||!variant?.stock||!p.stock} onClick={enter}>{busy?'正在揭晓…':!variant?.stock||!p.stock?'所选规格已发完':info&&!info.mock?'抽奖尚未开放':'免费参与抽奖'}</button>}</section>;
}
