'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,ApiError,errorText,money,date,type Member,type Order} from '@/lib/api';
import {Wallet,Ticket,Handbag,Gift,SignOut,IdentificationCard,Key,House} from './icons';
import {ProfileEditor,PasswordEditor} from './account-editors';
import RechargeCenter from './recharge-center';
type Section='account'|'profile'|'password'|'recharge'|'newcomer';
const routes={account:'/account',profile:'/account/profile',password:'/account/password',recharge:'/offers/recharge',newcomer:'/offers/newcomer'};
const names={account:'个人中心',profile:'修改个人信息',password:'修改密码',recharge:'充值中心',newcomer:'我的优惠券'};
const groups=[{label:'账户',links:[['account','我的主页','/account',House]]},{label:'个人资料',links:[['profile','修改个人信息','/account/profile',IdentificationCard],['password','修改密码','/account/password',Key]]},{label:'财务',links:[['recharge','充值中心','/offers/recharge',Wallet],['orders','购买记录','/orders?tab=mine',Handbag],['newcomer','我的优惠券','/offers/newcomer',Gift]]},{label:'服务',links:[['tickets','我的工单','/tickets',Ticket]]}] as const;
export default function MemberArea({section}:{section:Section}){
  const router=useRouter();const [me,setMe]=useState<Member|null>(null),[orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const [m,o]=await Promise.all([api<Member>('/me'),section==='account'?api<{items:Order[]}>('/orders?page_size=5'):Promise.resolve({items:[] as Order[]})]);setMe(m);setOrders(o.items);}catch(e){if(e instanceof ApiError&&e.status===401)router.replace(`/login?next=${encodeURIComponent(routes[section])}`);else setError(errorText(e));}}
  useEffect(()=>{setError('');setMessage('');void load();},[section]);
  async function claim(){setBusy(true);setError('');try{await api('/coupons/newcomer',{});await load();setMessage('新人优惠券已到账，下单时可选择使用');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await api('/auth/logout',{});router.push('/login');router.refresh();}catch(e){setError(errorText(e));setBusy(false);}}
  if(!me)return <main id="main" className="site-main"><div className="loading">{error?<><p role="alert" className="error-message">{error}</p><button className="secondary" onClick={load}>重新加载</button></>:'正在加载你的账户…'}</div></main>;
  return <main id="main" className="site-main"><header className="page-hero"><span className="eyebrow">MEMBER CENTER</span><h1>{names[section]}</h1><p>管理个人资料、购买记录与账户余额。</p></header><div className="member-layout account-layout"><aside className="panel member-menu account-menu">{groups.map(g=><section key={g.label}><small>{g.label}</small>{g.links.map(([key,label,href,Icon])=><Link key={key} href={href} className={key===section?'active':''} aria-current={key===section?'page':undefined}><i><Icon size={21}/></i>{label}</Link>)}</section>)}<button onClick={logout} disabled={busy}><SignOut size={19}/>退出登录</button></aside><div className="workspace">{error?<p className="error-message" role="alert">{error}</p>:null}{message?<p className="notice" role="status">{message}</p>:null}
  {section==='account'?<><section className="panel account-head"><div><span className="eyebrow">WELCOME BACK</span><h2>你好，{me.display_name||me.email.split('@')[0]}</h2><p>{me.email}</p></div>{me.role==='admin'?<Link className="secondary" href="/admin">管理后台 →</Link>:<Link className="secondary" href="/">继续购物</Link>}</section><div className="stats"><div className="panel stat"><span>账户余额</span><strong>{money(me.balance)}</strong><Link href="/offers/recharge">前往充值中心 →</Link></div><div className="panel stat"><span>我的订单</span><strong>{me.orders.total}</strong><Link href="/orders?tab=mine">查看全部 →</Link></div><div className="panel stat"><span>可用优惠券</span><strong>{me.coupons.filter(c=>!c.used).length}</strong><Link href="/offers/newcomer">查看优惠 →</Link></div></div><section className="panel account-profile"><header className="member-section-heading"><i><IdentificationCard size={26}/></i><div><span className="eyebrow">PROFILE</span><h2>个人资料</h2></div><Link href="/account/profile">修改个人信息 →</Link></header><dl className="profile-grid">{[['登录账号',me.email],['注册时间',date(me.created)],['昵称',me.display_name||'未设置'],['联系电话',me.phone||'未设置'],['最近登录 IP',me.last_login_ip||'—'],['最近登录时间',me.last_login_at?date(me.last_login_at):'—'],['上次登录 IP',me.previous_login_ip||'—'],['上次登录时间',me.previous_login_at?date(me.previous_login_at):'—']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="panel recent-purchases"><header className="member-section-heading"><i><Handbag size={27}/></i><div><span className="eyebrow">RECENT PURCHASES</span><h2>最近购买</h2></div><Link href="/orders?tab=mine">全部记录 →</Link></header>{orders.length?<div className="purchase-table-scroll" role="region" aria-label="最近购买记录" tabIndex={0}><table className="purchase-table"><thead><tr>{['订单号','购买时间','商品','数量','金额','支付方式','付款状态','发货状态','操作'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td className="purchase-id">{o.id}<small>{o.source==='lottery'?'中奖订单':'商品订单'}</small></td><td>{date(o.created)}</td><td><div className="purchase-product"><img src={o.image} alt="" width={34} height={34}/><span>{o.name}<small>{o.variant_name}</small></span></div></td><td>{o.quantity}</td><td className="purchase-money">{money(o.total)}</td><td>{({mock:'模拟支付',alipay:'支付宝',wechat:'微信支付',balance:'余额'})[o.payment_method]}</td><td><span className={`status ${o.status}`}>{o.status==='paid'?'已支付':o.status==='pending'?'待付款':'已关闭'}</span></td><td><span className={`status ${o.status==='paid'?'paid':''}`}>{o.status==='paid'?'已交付':o.status==='pending'?'待付款':'未交付'}</span></td><td><Link className="purchase-view" href={`/orders?tab=mine&order=${encodeURIComponent(o.id)}`}>查看订单</Link></td></tr>)}</tbody></table></div>:<div className="empty"><Handbag size={34}/><h3>暂无购买记录</h3><p>购买后的订单会显示在这里。</p><Link className="secondary" href="/">前往购物</Link></div>}</section></>:null}
  {section==='profile'?<ProfileEditor member={me} onSaved={load}/>:null}{section==='password'?<PasswordEditor/>:null}{section==='recharge'?<RechargeCenter member={me} onSaved={load}/>:null}
  {section==='newcomer'?<><section className="panel"><div className="offer-copy"><span className="eyebrow">NEW MEMBER EXCLUSIVE</span><h2>新人有礼，开启数字新体验</h2><p>新用户专属：满 ¥100 减 ¥10，每个账号可领取一次。</p></div><button className="primary" disabled={busy||me.coupons.some(c=>c.kind==='newcomer')} onClick={claim}>{me.coupons.some(c=>c.kind==='newcomer')?'已领取新人优惠':'领取新人优惠券'}</button></section><section className="panel"><h2>我的优惠券</h2><div className="coupon-grid">{me.coupons.map(c=><div className={`coupon ${c.used?'used':''}`} key={c.id}><strong>{money(c.amount)}</strong><b>{c.kind==='newcomer'?'新人专属优惠':'ChatGPT Plus 抽奖优惠'}</b><small>满 {money(c.minimum)} 可用{c.kind.startsWith('lottery:')?' · 指定自助充值商品':''}</small>{c.used?<small>已使用</small>:<Link href={c.kind.startsWith('lottery:')?'/products/188':'/'}>去使用 →</Link>}</div>)}</div>{!me.coupons.length?<p>还没有优惠券，领取上方新人福利吧。</p>:null}</section></>:null}
  </div></div></main>;
}
