'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,ApiError,errorText,money,date,type Member,type Order} from '@/lib/api';
import {User,Wallet,Ticket,Handbag,Gift,SignOut,MagnifyingGlass} from './icons';
type Section='account'|'orders'|'tickets'|'recharge'|'newcomer';
const routes={account:'/account',orders:'/orders',tickets:'/tickets',recharge:'/offers/recharge',newcomer:'/offers/newcomer'};
const names={account:'个人中心',orders:'我的订单',tickets:'工单中心',recharge:'充值优惠',newcomer:'新人优惠'};
const menu=[['account','个人中心',User],['orders','我的订单',Handbag],['recharge','余额充值',Wallet],['newcomer','我的优惠',Gift],['tickets','提交工单',Ticket]] as const;
type SupportTicket={id:string;title:string;body:string;status:string;order_id:string|null;created:number};
export default function MemberArea({section}:{section:Section}){
  const router=useRouter();
  const [me,setMe]=useState<Member|null>(null),[orders,setOrders]=useState<Order[]>([]),[tickets,setTickets]=useState<SupportTicket[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[amount,setAmount]=useState(10000);
  async function load(){try{const [m,o,t]=await Promise.all([api<Member>('/me'),api<{items:Order[]}>('/orders'),api<{items:SupportTicket[]}>('/tickets')]);setMe(m);setOrders(o.items);setTickets(t.items);}catch(e){if(e instanceof ApiError&&e.status===401){router.replace(`/login?next=${encodeURIComponent(routes[section])}`);}else setError(errorText(e));}}
  useEffect(()=>{void load();},[section]); // Refresh when navigating between account sections.
  async function action(task:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await task();setMessage(success);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function submitTicket(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setError('');setMessage('');try{await api('/tickets',{title:data.get('title'),body:data.get('body'),order_id:data.get('order_id')||null});form.reset();setMessage('工单已提交，可在下方查看。演示环境无真实客服回复。');await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  if(!me)return <main id="main" className="site-main"><div className="loading">{error?<><p className="error-message" role="alert">{error}</p><button className="secondary" onClick={load}>重新加载</button></>:'正在加载你的账户…'}</div></main>;
  const filtered=orders.filter(o=>(filter==='all'||o.status===filter)&&`${o.id} ${o.name}`.toLowerCase().includes(query.toLowerCase()));
  return <main id="main" className="site-main"><div className="page-hero"><span className="eyebrow">MEMBER CENTER</span><h1>{names[section]}</h1><p>管理账户、购买记录和售后服务，让每一次数字体验更简单。</p></div><div className="member-layout"><aside className="panel member-menu">{menu.map(([key,label,Icon])=><Link className={section===key?'active':''} href={routes[key]} key={key}><Icon size={19}/>{label}</Link>)}<button disabled={busy} onClick={()=>action(async()=>{await api('/auth/logout',{});router.push('/login');},'已退出登录')}><SignOut size={19}/>退出登录</button></aside><div className="workspace">{error?<p className="error-message" role="alert">{error}</p>:null}{message?<p className="notice" role="status">{message}</p>:null}
  {section==='account'?<><section className="panel account-head"><div><span className="eyebrow">WELCOME BACK</span><h2>你好，{me.email.split('@')[0]}</h2><p>{me.email}</p></div><Link className="secondary" href="/">继续购物</Link></section><div className="stats"><div className="panel stat"><span>账户余额</span><strong>{money(me.balance)}</strong><Link href="/offers/recharge">立即充值 →</Link></div><div className="panel stat"><span>我的订单</span><strong>{me.orders.total}</strong><Link href="/orders">查看全部 →</Link></div><div className="panel stat"><span>可用优惠券</span><strong>{me.coupons.filter(c=>!c.used).length}</strong><Link href="/offers/newcomer">查看优惠 →</Link></div></div><section className="panel"><h2>账户信息</h2><div className="summary-line"><span>注册邮箱</span><span>{me.email}</span></div><div className="summary-line"><span>注册时间</span><span>{date(me.created)}</span></div><div className="summary-line"><span>账号安全</span><Link href="/login">前往登录页找回密码</Link></div><p>当前为本地演示账户，与参考网站账号不互通。</p></section><section className="panel"><h2>充值记录</h2>{me.ledger.length?me.ledger.map(l=><div className="summary-line" key={l.id}><span>{date(l.created)}</span><span>模拟充值 {money(l.amount)} · 赠送 {money(l.bonus)}</span></div>):<p>暂无充值记录。</p>}</section></>:null}
  {section==='orders'?<><label className="search-field order-search"><MagnifyingGlass size={18}/><input type="search" aria-label="搜索订单" value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入订单号或商品名称"/></label><div className="filters">{[['all','全部订单'],['pending','待付款'],['paid','已完成'],['cancelled','已取消']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}</button>)}</div>{filtered.length?filtered.map(o=><article key={o.id} className="panel order-card"><header><div><code>{o.id}</code><time>{date(o.created)}</time></div><span className={`status ${o.status}`}>{({pending:'待付款',paid:'已完成',cancelled:'已取消'})[o.status]}</span></header><div className="order-body"><img src={o.image} alt="" width={52} height={52}/><div><h3>{o.name}</h3><p>{o.variant_name} · 数量 × {o.quantity} · 接收邮箱：{o.account}</p>{o.discount>0?<p>已优惠 {money(o.discount)}</p>:null}</div><strong>{money(o.total)}</strong></div>{o.delivery?<div className="delivery"><strong>交付信息</strong>{o.delivery}</div>:null}<div className="order-actions">{o.status==='pending'?<><button className="secondary" disabled={busy} onClick={()=>action(()=>api(`/orders/${o.id}/cancel`,{}),'订单已取消')}>取消订单</button><button className="primary" disabled={busy} onClick={()=>action(()=>api(`/orders/${o.id}/pay`,{method:o.payment_method}),'模拟支付成功，未产生真实扣款')}>{({mock:'模拟支付',alipay:'模拟支付宝支付',wechat:'模拟微信支付',balance:'余额支付'})[o.payment_method]} {money(o.total)}</button></>:<Link className="secondary" href="/tickets">联系售后</Link>}</div></article>):<section className="panel empty"><Handbag size={36}/><h3>暂无相关订单</h3><p>购买记录会显示在这里。</p><Link className="secondary" href="/">去逛逛商品</Link></section>}</>:null}
  {section==='tickets'?<><section className="panel"><h2>提交新工单</h2><form className="stack-form" onSubmit={submitTicket}><label><span>关联订单（选填）</span><select name="order_id"><option value="">一般咨询 / 不关联订单</option>{orders.map(o=><option key={o.id} value={o.id}>{o.id} · {o.name}</option>)}</select></label><label><span>问题标题</span><input required name="title" minLength={3} maxLength={100} placeholder="简要描述你遇到的问题"/></label><label><span>问题详情</span><textarea required name="body" minLength={10} maxLength={3000} placeholder="请详细描述问题、发生时间和已经尝试的解决方法。请勿填写密码。"/></label><button className="primary" disabled={busy}>{busy?'提交中…':'提交工单'}</button></form></section><section className="panel"><h2>我的工单</h2>{tickets.length?tickets.map(t=><article className="ticket-item" key={t.id}><header><h3>{t.title}</h3><span className="status">待处理</span></header><p>{t.body}</p><small>{t.id} · {date(t.created)}{t.order_id?` · 订单 ${t.order_id}`:''}</small></article>):<p>暂无工单，需要帮助时可使用上方表单。</p>}</section></>:null}
  {section==='recharge'?<section className="panel"><div className="offer-copy"><span className="eyebrow">RECHARGE OFFERS</span><h2>充值享好礼，余额更超值</h2><p>选择充值金额，赠送余额自动到账。</p></div><p className="notice">当前为模拟充值，不会扣款。余额仅用于本站演示购物。</p><p>当前余额 <strong>{money(me.balance)}</strong></p><div className="recharge-grid">{[[10000,500],[30000,2000],[50000,5000]].map(([a,b])=><button className={amount===a?'active':''} onClick={()=>setAmount(a)} key={a}><strong>{money(a)}</strong><span>加赠 {money(b)}</span></button>)}</div><button className="primary wide" disabled={busy} onClick={()=>action(()=>api('/recharges',{amount,request_key:crypto.randomUUID()}),'模拟充值成功，余额已更新')}>{busy?'处理中…':`确认模拟充值 ${money(amount)}`}</button></section>:null}
  {section==='newcomer'?<><section className="panel"><div className="offer-copy"><span className="eyebrow">NEW MEMBER EXCLUSIVE</span><h2>新人有礼，开启数字新体验</h2><p>新用户专属：满 ¥100 减 ¥10，每个账号可领取一次。</p></div><button className="primary" disabled={busy||me.coupons.some(c=>c.kind==='newcomer')} onClick={()=>action(()=>api('/coupons/newcomer',{}),'新人优惠券已到账，下单时可选择使用')}>{me.coupons.some(c=>c.kind==='newcomer')?'已领取新人优惠':'领取新人优惠券'}</button></section><section className="panel"><h2>我的优惠券</h2><div className="coupon-grid">{me.coupons.map(c=><div className={`coupon ${c.used?'used':''}`} key={c.id}><strong>{money(c.amount)}</strong><b>{c.kind==='newcomer'?'新人专属优惠':'ChatGPT Plus 抽奖优惠'}</b><small>满 {money(c.minimum)} 可用{c.kind.startsWith('lottery:')?' · 指定自助充值商品':''}</small>{c.used?<small>已使用</small>:<Link href={c.kind.startsWith('lottery:')?'/products/188':'/'}>去使用 →</Link>}</div>)}</div>{!me.coupons.length?<p>还没有优惠券，领取上方新人福利吧。</p>:null}</section></>:null}
  </div></div></main>;
}
