'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {api,errorText,money,date,type Order} from '@/lib/api';
import {CheckCircle,Clock,Copy,X,ArrowRight} from './icons';
const methods={mock:'模拟支付',alipay:'支付宝',wechat:'微信支付',balance:'余额付款'};
export function cacheOrder(id:string){try{const existing=JSON.parse(localStorage.getItem('piusgo.orders.v1')||'[]');localStorage.setItem('piusgo.orders.v1',JSON.stringify([id,...(Array.isArray(existing)?existing:[]).filter(x=>typeof x==='string'&&x!==id)].slice(0,20)));}catch{/* Private browsing may disable storage; order number remains visible. */}}
function Countdown({expires}:{expires:number}){const [left,setLeft]=useState<number|null>(null);useEffect(()=>{function tick(){setLeft(Math.max(0,Math.floor(expires-Date.now()/1000)));}tick();const t=setInterval(tick,1000);return()=>clearInterval(t);},[expires]);return <span>{left===null?'--:--':`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}</span>;}
type PaymentSession={qr_image:string;expires_at:number;mock:boolean;method:Order['payment_method']};
function PaymentDialog({order,close,update}:{order:Order;close:()=>void;update:(o:Order)=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [session,setSession]=useState<PaymentSession|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const d=dialog.current;d?.showModal();let active=true;api<PaymentSession>(`/orders/${order.id}/payment-session`,{}).then(x=>{if(active)setSession(x);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;d?.close();};},[order.id]);
  async function pay(){setBusy(true);setError('');try{const next=await api<Order>(`/orders/${order.id}/pay`,{method:order.payment_method});update(next);close();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <dialog className="payment-dialog" ref={dialog} onCancel={close}><button className="dialog-close icon-button" aria-label="关闭支付弹窗" onClick={close}><X size={22}/></button><h2>{methods[order.payment_method]}{order.payment_method==='balance'?'':'扫码'}支付</h2><p>{order.payment_method==='balance'?'使用账户演示余额完成付款':'请使用手机扫描二维码完成付款'}</p><div className="mock-payment-label">模拟支付 · 二维码不具备真实收款功能</div>{session&&order.payment_method!=='balance'?<div className="payment-qr"><img className="qr-code" src={session.qr_image} alt="本地模拟支付二维码" width={320} height={320}/>{order.payment_method==='alipay'||order.payment_method==='wechat'?<img className="qr-brand" src={`/assets/payment-${order.payment_method}.png`} alt="" width={35} height={35}/>:null}</div>:!session&&!error?<p role="status">正在创建支付信息…</p>:null}<div className="summary-line"><span>订单号</span><b>{order.id}</b></div><div className="summary-line"><span>应付金额</span><strong className="payment-amount">{money(order.total)}</strong></div><div className="summary-line"><span>支付倒计时</span><b className="payment-time"><Countdown expires={order.expires_at}/></b></div>{error?<p className="error-message" role="alert">{error}</p>:null}<button className="primary wide" disabled={!session||busy} onClick={pay}>{busy?'确认支付中…':order.payment_method==='balance'?'确认余额付款':'模拟付款成功'}</button><button className="secondary wide" onClick={close}>查看订单</button></dialog>;
}
export default function OrderReceipt({initial,openPayment=false}:{initial:Order;openPayment?:boolean}){
  const [order,setOrder]=useState(initial),[open,setOpen]=useState(openPayment&&initial.status==='pending'),[error,setError]=useState(''),[copied,setCopied]=useState(false),[email,setEmail]=useState<{subject:string;body:string}|null>(null);
  useEffect(()=>{setOrder(initial);setOpen(openPayment&&initial.status==='pending');setEmail(null);setError('');},[initial,openPayment]);
  useEffect(()=>{if(order.status==='cancelled'||(order.status==='paid'&&['sent','mock_delivered','failed','not_requested'].includes(order.email_status||'')))return;let active=true,timer:ReturnType<typeof setTimeout>;let failures=0;async function poll(){try{const next=await api<Order>(`/orders/${order.id}/status`);if(!active)return;setOrder(next);setError('');failures=0;if(next.status!=='pending')setOpen(false);if(next.status==='cancelled'||(next.status==='paid'&&['sent','mock_delivered','failed','not_requested'].includes(next.email_status||'')))return;}catch(e){if(!active)return;failures++;setError(`状态查询暂时失败，将自动重试：${errorText(e)}`);}if(active)timer=setTimeout(poll,Math.min(15000,3000*(failures+1)));}timer=setTimeout(poll,2000);return()=>{active=false;clearTimeout(timer);};},[order.id,order.status,order.email_status]);
  async function copy(){try{await navigator.clipboard.writeText(order.id);setCopied(true);}catch{setError('复制失败，请手动保存订单号。');}}
  async function showMail(){try{setEmail(await api(`/orders/${order.id}/email`));}catch(e){setError(errorText(e));}}
  return <section className="order-receipt"><header className="receipt-heading"><i><CheckCircle size={43}/></i><div><span className="eyebrow">{order.status==='paid'?'PAYMENT COMPLETED':'ORDER CREATED'}</span><h1>{order.source==='lottery'?'中奖商品已发放':order.status==='paid'?'支付成功':order.status==='cancelled'?'订单已关闭':'订单已创建'}</h1><p>{order.status==='paid'?'交付内容已生成，请查看卡密与使用指南。':order.status==='cancelled'?'订单已取消或支付超时，请重新下单。':'请在有效时间内完成支付。'}</p></div><span className={`status ${order.status}`}>{order.status==='paid'?'已支付':order.status==='cancelled'?'已关闭':'待支付'}</span></header><div className="receipt-product"><img src={order.image} alt="" width={60} height={60}/><div><small>商品</small><h3>{order.name}–{order.variant_name}</h3><span>数量 × {order.quantity}</span></div><strong>{money(order.total)}</strong></div><div className="receipt-meta"><div>{order.payment_method==='alipay'||order.payment_method==='wechat'?<img src={`/assets/payment-${order.payment_method}.png`} alt="" width={30} height={30}/>:<Clock size={27}/>}<span><small>支付方式</small><b>{order.source==='lottery'?'免费抽奖 · 无需付款':methods[order.payment_method]}</b></span></div><div><Clock size={27}/><span><small>创建时间</small><b>{date(order.created)}</b></span></div></div><div className="receipt-number"><span>订单号</span><button onClick={copy} title="复制订单号"><b>{order.id}</b><Copy size={17}/></button></div>{copied?<p className="receipt-hint" role="status">订单号已复制</p>:null}
    {order.status==='pending'?<><button className="primary wide" onClick={()=>setOpen(true)}>继续支付 <ArrowRight size={18}/></button><p className="receipt-hint">剩余支付时间 <Countdown expires={order.expires_at}/> · 请妥善保存订单号</p></>:null}
    {order.status==='paid'?<section className="receipt-delivery"><h2>交付内容</h2><pre>{order.delivery}</pre><p>接收邮箱：{order.account}</p><p className="notice">{order.email_status==='not_requested'?'历史订单未生成交付邮件，卡密仍可在本页查看。':order.email_status==='sent'?'交付邮件已发送。':order.email_status==='mock_delivered'?'模拟邮件已保存至本地收件箱，未向外部邮箱发送。':order.email_status==='failed'?'邮件发送失败，卡密仍可在本页查看，请提交工单。':'交付邮件正在排队发送…'}</p>{order.email_status!=='not_requested'?<button className="secondary" onClick={showMail}>查看交付邮件</button>:null}{email?<div className="mail-preview"><h3>{email.subject}</h3><pre>{email.body}</pre></div>:null}<h2>使用指南</h2><ol>{order.usage_guide.map(item=><li key={item}>{item}</li>)}</ol><Link className="secondary" href={`/tickets/new?order=${encodeURIComponent(order.id)}`}>申请售后 / 创建工单</Link></section>:null}
    <Link className="secondary wide" href={order.kind==='member'?'/orders?tab=mine':'/orders'}>查看订单</Link><p className="receipt-hint">游客订单可凭完整订单号查询，请勿向无关人员泄露。</p>{error?<p className="error-message" role="alert">{error}</p>:null}{open?<PaymentDialog order={order} close={()=>setOpen(false)} update={setOrder}/>:null}</section>;
}
