'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {api,errorText,money,date,type Member,type Order} from '@/lib/api';
import {MagnifyingGlass,ShieldCheck,Handbag} from './icons';
import OrderReceipt,{cacheOrder} from './order-receipt';
export default function OrderLookup(){
  const params=useSearchParams();const [user,setUser]=useState<Member|null>(null),[ready,setReady]=useState(false),[tab,setTab]=useState<'guest'|'mine'|'cache'>('guest'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<Order|null>(null),[items,setItems]=useState<Order[]>([]),[cached,setCached]=useState<string[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0);
  useEffect(()=>{let active=true;api<{user:Member|null}>('/checkout/session').then(d=>{if(active){setUser(d.user);setTab(params.get('tab')==='mine'?'mine':d.user?'mine':'guest');}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setReady(true);});try{const ids=JSON.parse(localStorage.getItem('piusgo.orders.v1')||'[]');setCached(Array.isArray(ids)?ids.filter(x=>typeof x==='string').slice(0,20):[]);}catch{}return()=>{active=false;};},[params]);
  useEffect(()=>{if(tab!=='mine'||!user)return;let active=true;setBusy(true);api<{items:Order[];total:number}>(`/orders?page=${page}&page_size=10`).then(d=>{if(active){setItems(d.items);setTotal(d.total);}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[tab,user,page]);
  useEffect(()=>{const id=params.get('order');if(!ready||!id)return;let active=true;api<Order>('/orders/lookup',{order_id:id}).then(o=>{if(active)setResult(o);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[ready,params]);
  function switchTab(next:'guest'|'mine'|'cache'){setTab(next);setResult(null);setQuery('');setError('');setPage(1);}
  async function lookup(id:string){setBusy(true);setError('');setResult(null);try{const d=await api<Order>('/orders/lookup',{order_id:id.trim()});if(tab==='guest'&&d.kind!=='guest')throw new Error('这是会员订单，请切换到我的订单查看');if(tab==='mine'&&d.kind!=='member')throw new Error('这是游客订单，请切换到游客订单查看');setResult(d);cacheOrder(d.id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <main id="main" className="site-main lookup-page"><header className="lookup-hero"><div><span className="eyebrow">ORDER LOOKUP</span><h1>订单查询</h1><p>查询付款状态、发货状态与已购买的卡密。</p></div><div><button className="dark-button" onClick={()=>switchTab('mine')}>我的全部订单</button><Link className="secondary" href="/tickets">提交工单</Link></div></header><section className="lookup-panel"><header><div><span className="eyebrow">QUICK LOOKUP</span><h2>查订单与卡密</h2></div><div className="segment-tabs" role="tablist" aria-label="订单类型">{([['mine','我的订单'],['guest','游客订单'],['cache','缓存查单']] as const).map(([key,title])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>switchTab(key)}>{title}</button>)}</div></header>
  {tab==='mine'&&ready&&!user?<div className="empty"><Handbag size={35}/><h3>登录后查看我的订单</h3><p>游客订单无需登录，可切换到游客订单查询。</p><Link className="primary" href="/login?next=%2Forders%3Ftab%3Dmine">登录 / 注册</Link></div>:tab==='cache'?<div className="lookup-form"><h3>检测到 {cached.length} 笔本机订单缓存</h3><p>仅保存订单号，不缓存卡密或邮箱。清除浏览器数据后将失效。</p>{cached.map(id=><button className="cached-order" key={id} onClick={()=>lookup(id)}>{id}<span>查询订单 →</span></button>)}{cached.length?<button className="secondary" onClick={()=>{localStorage.removeItem('piusgo.orders.v1');setCached([]);setResult(null);}}>清空缓存</button>:null}</div>:<form className="lookup-form" onSubmit={e=>{e.preventDefault();void lookup(query);}}><div className="lookup-label"><b>订单号</b><span>{tab==='guest'?'输入完整游客订单号，无需登录':'仅查询当前账号的订单'}</span></div><div className="lookup-input-row"><label><MagnifyingGlass size={23}/><input required minLength={3} maxLength={50} value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入订单号" aria-label="订单号" autoComplete="off"/></label><button className="primary" disabled={busy}><MagnifyingGlass size={22}/>{busy?'查询中…':'立即查询'}</button></div><p><ShieldCheck size={18}/>会员订单需登录本人账号；请妥善保管游客订单号。</p></form>}
  {error?<p className="error-message lookup-error" role="alert">{error}</p>:null}{result?<div className="lookup-result"><OrderReceipt initial={result}/></div>:tab==='mine'&&user?<div className="lookup-result">{items.length?items.map(o=><article className="lookup-order-card" key={o.id}><header><span className={`status ${o.status}`}>{o.status==='paid'?'已完成':o.status==='pending'?'待付款':'已关闭'}</span><strong>{money(o.total)}</strong></header><h3>{o.id}</h3><p>下单时间：{date(o.created)}</p><div className="order-body"><img src={o.image} alt="" width={45} height={45}/><div><h3>{o.name}</h3><p>{o.variant_name} · 数量 {o.quantity}</p></div><button className="secondary" onClick={()=>setResult(o)}>查看订单</button></div></article>):<div className="empty"><Handbag size={35}/><h3>还没有订单记录</h3><Link href="/" className="secondary">去购物</Link></div>}<div className="pagination"><span>共 {total} 条</span><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(total/10))} 页</span><button disabled={page>=Math.ceil(total/10)||busy} onClick={()=>setPage(p=>p+1)}>下一页</button></div></div>:!(tab==='mine'&&!user)?<div className="empty lookup-empty"><MagnifyingGlass size={42}/><h3>等待查询</h3><p>订单结果会显示在这里</p></div>:null}</section></main>;
}
