'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {type Catalog,type Lottery,money} from '@/lib/api';
import {MagnifyingGlass,UploadSimple,Star,ArrowRight} from './icons';
function Countdown({end}:{end:number}) {
  const [seconds,setSeconds]=useState<number|null>(null);
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,end-Math.floor(Date.now()/1000)));tick();const timer=setInterval(tick,1000);return ()=>clearInterval(timer);},[end]);
  return <strong className="countdown">{seconds===null?'--:--:--':[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,'0')).join(':')}</strong>;
}
export default function Store({catalog,lottery}:{catalog:Catalog;lottery:Lottery}) {
  const [category,setCategory]=useState(0),[query,setQuery]=useState(''),[share,setShare]=useState('');
  const items=catalog.items.filter(p=>(category===0||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase()));
  const showLottery=category===0&&(!query||'ChatGPT Plus 抽奖'.toLowerCase().includes(query.toLowerCase()));
  const selected=catalog.categories.find(c=>c.id===category)?.name||'热销';
  async function shareStore(){try{await navigator.clipboard.writeText(location.origin);setShare('店铺链接已复制');}catch{setShare(`店铺链接：${location.origin}`);}}
  return <main id="main" className="site-main home-main"><section className="home-heading"><div><span className="eyebrow">DIGITAL SERVICES</span><h1>选择你需要的数字服务</h1><p>价格、库存与交付状态实时展示，点击商品即可进入详情和下单页面。</p></div><div className="heading-actions"><label className="search-field"><MagnifyingGlass size={19}/><input aria-label="搜索商品名称" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索商品名称" type="search"/></label><button className="secondary share" onClick={shareStore}><UploadSimple size={18}/>分享店铺</button></div></section>{share?<p className="notice" role="status">{share}<button onClick={()=>setShare('')}>关闭</button></p>:null}<div className="catalog-layout"><aside className="category-panel"><header><span className="eyebrow">CATEGORIES</span><h2>商品分类</h2></header><nav className="category-list" aria-label="商品分类"><button className={`category-item ${category===0?'active':''}`} onClick={()=>setCategory(0)}><i className="category-hot"><Star size={20}/></i><span>热销</span><b>{catalog.items.length+1}</b></button>{catalog.categories.map(c=><button key={c.id} className={`category-item ${category===c.id?'active':''}`} onClick={()=>setCategory(c.id)}><img src={c.image} alt="" width={34} height={34}/><span>{c.name}</span><b>{catalog.items.filter(p=>p.category===c.id).length}</b></button>)}</nav></aside><section className="catalog-products"><header className="section-heading"><div><span className="eyebrow">STORE</span><h2>{selected}</h2></div><span aria-live="polite">{items.length+(showLottery?1:0)} 件商品</span></header><div className="product-grid">{showLottery?<Link href="/lottery" className="product-card lottery-card"><div className="product-top"><img src="/assets/brand-0.png" alt="" width={58} height={58}/><span className="badge">抽奖商品</span></div><h3>ChatGPT–Plus 官方充值成品号</h3><p className="lottery-market">奖品价值 {money(14800)}</p><div className="lottery-count"><span>已有 <b>{lottery.participants}</b> 人参与</span><span>每日 1 次</span></div><div className="lottery-bottom"><div><small>本期活动倒计时</small><Countdown end={lottery.ends_at}/></div><span className="lottery-action">参与抽奖 <ArrowRight size={14}/></span></div></Link>:null}{items.map(p=><Link className="product-card" href={`/products/${p.id}`} key={p.id}><div className="product-top"><img src={p.image} alt="" width={58} height={58}/><span className="badge">{p.stock===0?'已售罄':p.badge}</span></div><h3>{p.name}</h3><div className="product-tags">{p.tags.map((tag,i)=><span className={`tone-${i%3}`} key={tag}>{tag}</span>)}</div><div className="product-bottom"><span className="product-price"><small>到手价</small><strong>{money(p.price)}</strong></span><span className="stock">{p.stock===0?'暂时缺货':p.stock>=999?'库存充足':`库存 ${p.stock}`}</span></div></Link>)}</div>{items.length===0&&!showLottery?<div className="empty"><MagnifyingGlass size={35}/><h3>没有找到相关商品</h3><p>换个关键词，或查看其他分类。</p><button className="secondary" onClick={()=>{setQuery('');setCategory(0);}}>查看全部商品</button></div>:null}</section></div></main>;
}
