'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,errorText,date} from '@/lib/api';
import {Ticket,Headset,ChatCircleDots,CheckCircle,ShieldCheck,PlusCircle,MagnifyingGlass} from './icons';
const statuses=[['all','全部工单',Ticket],['open','待客服回复',Headset],['waiting_user','待我回复',ChatCircleDots],['resolved','已经解决',CheckCircle],['closed','已经关闭',ShieldCheck]] as const;
type Item={id:string;title:string;body:string;order_id:string;priority:'low'|'medium'|'high';status:string;created:number};
export default function TicketCenter(){
  const [data,setData]=useState<{items:Item[];total:number;counts:Record<string,number>}>({items:[],total:0,counts:{}}),[ready,setReady]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[size,setSize]=useState(20),[jump,setJump]=useState('1'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;api('/checkout/session').then(()=>{if(active)setReady(true);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[]);
  useEffect(()=>{if(!ready)return;let active=true;setBusy(true);const t=setTimeout(()=>{api<typeof data>(`/tickets?q=${encodeURIComponent(query)}&status=${status}&page=${page}&page_size=${size}`).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setBusy(false);});},250);return()=>{active=false;clearTimeout(t);};},[ready,query,status,page,size]);
  const pages=Math.max(1,Math.ceil(data.total/size));
  return <main id="main" className="site-main ticket-center"><header className="ticket-hero"><div><span className="eyebrow"><ShieldCheck size={18}/>专属支持中心</span><h1>我的工单</h1><p>购买后需要帮助，都可以在这里查看工单和跟进问题。</p></div><Link className="dark-button" href="/tickets/new"><PlusCircle size={24}/>创建工单<PlusCircle size={18}/></Link></header><div className="ticket-stats">{statuses.map(([key,label,Icon],i)=><button className={status===key?'active':''} key={key} onClick={()=>{setStatus(key);setPage(1);}}><i className={`ticket-tone-${i}`}><Icon size={27}/></i><span><small>{label}</small><strong>{key==='all'?Object.values(data.counts).reduce((a,b)=>a+b,0):data.counts[key]||0}</strong></span></button>)}</div><section className="ticket-records"><header><div><Ticket size={31}/><span><small>TICKET RECORDS</small><h2>工单记录</h2></span></div><label className="search-field"><MagnifyingGlass size={18}/><input type="search" aria-label="搜索工单号或标题" placeholder="搜索工单号或标题" value={query} maxLength={100} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label></header>{error?<p className="error-message" role="alert">{error}</p>:null}{busy?<p className="loading" role="status">正在查询工单…</p>:data.items.length?<div className="ticket-list">{data.items.map(t=><details className="ticket-record" key={t.id}><summary><div><b>{t.title}</b><small>{t.id} · {date(t.created)}</small></div><span className={`priority ${t.priority}`}>{({low:'低',medium:'中',high:'高'})[t.priority]}优先级</span><span className="status">{statuses.find(x=>x[0]===t.status)?.[1]||t.status}</span></summary><p>关联订单：{t.order_id}</p><p className="ticket-body-text">{t.body}</p><small>演示环境会保存工单，尚未接入人工客服回复。</small></details>)}</div>:<div className="empty ticket-empty"><i><Ticket size={44}/></i><h3>{query?'没有找到匹配的工单':'这里还没有工单'}</h3><p>{query?'试试其他标题或完整工单号。':'创建第一张工单后可以在这里持续跟进'}</p></div>}<div className="pagination"><span>共 {data.total} 条</span><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第</span><input type="number" min={1} max={pages} aria-label="跳转页码" value={jump} onChange={e=>setJump(e.target.value)}/><span>/ {pages} 页</span><button disabled={busy} onClick={()=>{const n=Number(jump);if(Number.isInteger(n)&&n>=1&&n<=pages)setPage(n);}}>跳页</button><button disabled={page>=pages||busy} onClick={()=>setPage(p=>p+1)}>下一页</button><label>每页 <select aria-label="每页工单数" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[10,20,50,100].map(n=><option key={n} value={n}>{n} 条</option>)}</select></label><span>当前第 {page} 页</span></div></section></main>;
}
