'use client';
import {useEffect,useRef,useState} from 'react';
import {api,errorText} from '@/lib/api';
import {type ChatMessage,type Conversation} from './use-chat';
import {ArrowRight,X} from '../icons';
export function Transcript({messages,conversation,actor,older,loadOlder,onBottom}:{messages:ChatMessage[];conversation:Conversation|null;actor:'customer'|'agent';older:boolean;loadOlder:()=>Promise<void>;onBottom:(v:boolean)=>void}){
  const area=useRef<HTMLDivElement>(null),stick=useRef(true),previousFirst=useRef<number|null>(null);const [error,setError]=useState('');
  useEffect(()=>{const el=area.current;if(!el)return;const first=messages[0]?.seq||null;if(previousFirst.current===first||previousFirst.current===null){if(stick.current)el.scrollTop=el.scrollHeight;}previousFirst.current=first;},[messages]);
  async function earlier(){const el=area.current,oldHeight=el?.scrollHeight||0,oldTop=el?.scrollTop||0;try{await loadOlder();requestAnimationFrame(()=>{if(el)el.scrollTop=oldTop+el.scrollHeight-oldHeight;});}catch(e){setError(errorText(e));}}
  return <div className="chat-transcript" ref={area} onScroll={e=>{const el=e.currentTarget;stick.current=el.scrollHeight-el.scrollTop-el.clientHeight<70;onBottom(stick.current);}} aria-live="polite" aria-relevant="additions text">{older?<button className="chat-history" onClick={earlier}>加载更早的消息</button>:null}{error?<p className="error-message">{error}</p>:null}{!messages.length?<p className="chat-welcome">您好，欢迎联系在线客服。请描述您的问题，我们会在接待后回复。请勿发送密码或完整卡密。</p>:null}{messages.map(m=><article className={`chat-message ${m.sender_role===actor?'outgoing':'incoming'}`} key={m.id}><small>{m.sender_role==='agent'?'客服':'客户'} · {new Date(m.created*1000).toLocaleString('zh-CN')}</small><div className="chat-bubble">{m.body?<p>{m.body}</p>:null}{m.attachment_id?<a href={`/api/support/attachments/${m.attachment_id}?actor=${actor}`} target="_blank" rel="noreferrer"><img loading="lazy" src={`/api/support/attachments/${m.attachment_id}?actor=${actor}`} alt="聊天截图"/></a>:null}</div>{m.sender_role===actor?<span className="chat-read">{conversation&&conversation.other_read_seq>=m.seq?'已读':'已发送'}</span>:null}</article>)}</div>;
}
export function Composer({cid,actor,send,disabled=false,prefill}:{cid:string;actor:'customer'|'agent';send:(body:string,key:string,aid:string|null)=>Promise<void>;disabled?:boolean;prefill?:{value:string;key:number}}){
  const [body,setBody]=useState(''),[attachment,setAttachment]=useState<string|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');const key=useRef(''),alive=useRef(true),picker=useRef<HTMLInputElement>(null);
  useEffect(()=>{alive.current=true;key.current=crypto.randomUUID();return()=>{alive.current=false;};},[cid]);
  useEffect(()=>{if(prefill){setBody(prefill.value);key.current=crypto.randomUUID();}},[prefill]);
  function changed(value:string){setBody(value);key.current=crypto.randomUUID();setError('');}
  async function upload(file:File){if(file.size>1000000){setError('截图不能超过 1 MB');return;}setUploading(true);setError('');try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api<{id:string}>('/support/attachments?actor='+actor,{conversation_id:cid,data});if(alive.current){setAttachment(result.id);key.current=crypto.randomUUID();}}catch(e){if(alive.current)setError(errorText(e));}finally{if(alive.current)setUploading(false);}}
  async function submit(){if(busy||uploading||disabled||(!body.trim()&&!attachment))return;setBusy(true);setError('');try{await send(body,key.current,attachment);if(alive.current){setBody('');setAttachment(null);key.current=crypto.randomUUID();}}catch(e){if(alive.current)setError('发送失败，可点击发送重试：'+errorText(e));}finally{if(alive.current)setBusy(false);}}
  return <div className="chat-composer"><div className="chat-tools"><button type="button" disabled={disabled||busy||uploading} onClick={()=>picker.current?.click()}>{uploading?'正在上传…':'添加截图'}</button><button type="button" disabled={disabled||busy} onClick={()=>changed(body+'🙂')}>表情</button><span>PNG / JPEG / WebP，≤ 1 MB</span><input ref={picker} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></div>{attachment?<div className="chat-attachment"><img src={`/api/support/attachments/${attachment}?actor=${actor}`} alt="待发送截图"/><button aria-label="移除待发送截图" disabled={busy} onClick={()=>{setAttachment(null);key.current=crypto.randomUUID();}}><X size={16}/></button></div>:null}<textarea value={body} maxLength={4000} disabled={disabled||busy} placeholder={disabled?'请先接待会话':'请输入您的问题，可直接粘贴截图'} onChange={e=>changed(e.target.value)} onPaste={e=>{const file=[...e.clipboardData.items].find(x=>x.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();void upload(file);}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit();}}}/>{error?<p className="chat-error" role="alert">{error}</p>:null}<footer><small>Enter 发送 · Shift+Enter 换行</small><button className="primary" disabled={busy||uploading||disabled||(!body.trim()&&!attachment)} onClick={submit}>{busy?'发送中…':'发送'}<ArrowRight size={16}/></button></footer></div>;
}
