'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,errorText,money} from '@/lib/api';
import {Headset,X} from '../icons';
import {CaretDown} from '@phosphor-icons/react/dist/ssr/CaretDown';
import {Composer,Transcript} from './chat-content';
import {useChat,type Conversation} from './use-chat';
import './support.css';
type Session={identity:string;conversation:Conversation;member:boolean;email:string};
type FAQ={id:number;category:string;question:string;answer:string};
function CustomerThread({session,open,reset,onUnread}:{session:Session;open:boolean;reset:()=>void;onUnread:(n:number)=>void}){
  const [bottom,setBottom]=useState(true),[email,setEmail]=useState(session.email),[note,setNote]=useState(''),[faqs,setFaqs]=useState<FAQ[]>([]),[faqOpen,setFaqOpen]=useState<number|null>(null),[category,setCategory]=useState(''),[orders,setOrders]=useState<{id:string;product_name:string;total:number}[]>([]);
  const [orderRevision,setOrderRevision]=useState(0);
  useEffect(()=>{const refresh=()=>setOrderRevision(v=>v+1);window.addEventListener('piusgo-orders-changed',refresh);return()=>window.removeEventListener('piusgo-orders-changed',refresh);},[]);
  const chat=useChat(session.conversation.id,'customer',open&&bottom,reset);
  useEffect(()=>{if(!open)return;let active=true;Promise.all([api<{items:FAQ[]}>('/support/faqs'),api<{items:typeof orders}>('/support/orders')]).then(([f,o])=>{if(active){setFaqs(f.items);setOrders(o.items);setCategory(f.items[0]?.category||'');}}).catch(e=>{if(active)setNote(errorText(e));});return()=>{active=false;};},[session.conversation.id,open,orderRevision]);
  useEffect(()=>{if(open&&bottom)onUnread(0);else onUnread(chat.conversation?.unread||0);},[open,bottom,chat.conversation?.unread,onUnread]);
  const categories=[...new Set(faqs.map(f=>f.category))];
  async function contact(){try{await api(`/support/conversations/${session.conversation.id}/contact`,{email});setNote('联系方式已保存；不会据此匹配其他人的订单。');}catch(e){setNote(errorText(e));}}
  async function bind(oid:string){if(!oid)return;try{await api(`/support/conversations/${session.conversation.id}/order`,{order_id:oid});setNote('订单已关联');}catch(e){setNote(errorText(e));}}
  return <><div className={`chat-identity ${session.member?'is-member':'is-guest'}`}><label><span>{session.member?'当前会员':'联系方式（未验证）'}</span><input type="email" value={email} maxLength={191} readOnly={session.member} aria-label="联系邮箱" onChange={e=>setEmail(e.target.value)} placeholder="邮箱（选填）"/></label>{!session.member?<button className="secondary" onClick={contact}>更新联系方式</button>:null}<label className="chat-order-field"><span>关联订单</span><div className="chat-order-select"><select aria-label="关联我的订单" value={chat.conversation?.order_id||''} onChange={e=>void bind(e.target.value)}><option value="" disabled>{orders.length?'请选择需要咨询的订单':'暂无可关联订单'}</option>{orders.map(o=><option key={o.id} value={o.id}>{o.product_name} · {money(o.total)} · 尾号 {o.id.slice(-8)}</option>)}</select><CaretDown size={15} weight="bold" aria-hidden="true"/></div></label></div><div className="chat-connection"><span className={chat.conversation?.online?'online':''}>{chat.conversation?.online?'客服在线':'客服离线，可直接留言'}</span><small>{chat.connection}</small></div>{note?<p className="chat-note" role="status">{note}<button aria-label="关闭提示" onClick={()=>setNote('')}>×</button></p>:null}{chat.error?<p className="chat-error" role="alert">{chat.error}</p>:null}<Transcript messages={chat.messages} conversation={chat.conversation} actor="customer" older={chat.older} loadOlder={chat.loadOlder} onBottom={setBottom}/>{!chat.messages.length?<section className="chat-faq"><h3>猜你想问</h3><nav aria-label="问题分类">{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</nav>{faqs.filter(f=>f.category===category).map(f=><div key={f.id}><button className="chat-faq-question" onClick={()=>setFaqOpen(faqOpen===f.id?null:f.id)}>{f.question}<span>›</span></button>{faqOpen===f.id?<p>{f.answer}</p>:null}</div>)}</section>:<details className="chat-faq compact"><summary>常见问题</summary>{faqs.map(f=><details key={f.id}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</details>}{chat.conversation?.order?<div className="chat-order-card">关联订单：{chat.conversation.order.product_name}<small>{chat.conversation.order.id.slice(-12)} · {money(chat.conversation.order.total)}</small></div>:null}{chat.conversation?.ticket_id?<Link className="chat-ticket-link" href="/tickets">已转工单，前往查看 →</Link>:null}<Composer key={session.conversation.id} cid={session.conversation.id} actor="customer" send={chat.send}/></>;
}
export default function SupportWidget({open,close,onUnread}:{open:boolean;close:()=>void;onUnread:(n:number)=>void}){
  const [session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);const generation=useRef(0),identity=useRef<string|null>(null),title=useRef<HTMLButtonElement>(null);
  const reset=useCallback(()=>{generation.current++;identity.current=null;setSession(null);setError('');onUnread(0);setRevision(v=>v+1);},[onUnread]);
  useEffect(()=>{const own=++generation.current;api<Session>('/support/session',{}).then(s=>{if(generation.current===own){identity.current=s.identity;setSession(s);}}).catch(e=>{if(generation.current===own)setError(errorText(e));});return()=>{generation.current++;};},[revision]);
  useEffect(()=>{const changed=()=>reset();const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('piusgo-auth'):null;if(channel)channel.onmessage=e=>{if(e.data==='changed')changed();};window.addEventListener('piusgo-auth-changed',changed);async function check(){if(document.hidden)return;const own=generation.current;try{const info=await api<{identity:string|null}>('/support/identity');if(generation.current===own&&identity.current&&info.identity!==identity.current)reset();}catch{/* Existing message connection handles temporary network errors. */}}const timer=setInterval(check,5000);window.addEventListener('focus',check);return()=>{channel?.close();window.removeEventListener('piusgo-auth-changed',changed);window.removeEventListener('focus',check);clearInterval(timer);};},[reset]);
  useEffect(()=>{if(open)title.current?.focus();},[open]);
  return <aside id="support-window" className="support-window" role="dialog" aria-labelledby="support-title" hidden={!open} onKeyDown={e=>{if(e.key==='Escape')close();}}><header><i><Headset size={27}/></i><div><h2 id="support-title">在线客服</h2><p>请描述问题；离线也可留言或<Link href="/tickets">提交工单</Link></p></div><button ref={title} aria-label="关闭在线客服" onClick={close}><X size={22}/></button></header>{session?<CustomerThread key={session.identity+session.conversation.id} session={session} open={open} reset={reset} onUnread={onUnread}/>:<div className="chat-loading">{error?<><p role="alert">{error}</p><button className="secondary" onClick={reset}>重新连接</button></>:'正在安全连接客服…'}</div>}</aside>;
}
