'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,ApiError,errorText,money} from '@/lib/api';
import {Composer,Transcript} from './chat-content';
import {useChat} from './use-chat';
import './support.css';
import FAQEditor from './faq-editor';
type Agent={id:string;name:string;role:string};
type QueueItem={id:string;status:string;assigned_to:string|null;updated:number;unread:number};
function DeskThread({id,agent,exit,refresh}:{id:string;agent:Agent;exit:()=>void;refresh:()=>void}){
  const [bottom,setBottom]=useState(true),[notice,setNotice]=useState(''),[agents,setAgents]=useState<{id:string;display_name:string}[]>([]),[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[ticket,setTicket]=useState(false),[prefill,setPrefill]=useState<{value:string;key:number}>();
  const chat=useChat(id,'agent',bottom,exit);
  useEffect(()=>{api<{items:typeof agents}>('/support/agent/agents').then(r=>setAgents(r.items)).catch(()=>{});},[id]);
  async function action(path:string,body:unknown,message:string){setBusy(true);setNotice('');try{await api(`/support/agent/conversations/${id}/${path}`,body);setNotice(message);refresh();if(path==='transfer')exit();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
  async function convert(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action('ticket',{title:f.get('title'),body:f.get('body'),priority:f.get('priority')},'已关联工单');}
  const c=chat.conversation;
  return <div className="desk-conversation"><section className="desk-chat"><header><div><h2>{c?.customer_name||'客户会话'}</h2><small>{chat.connection} · {c?.status==='closed'?'已结束':c?.status==='active'?'接待中':'等待接待'}</small></div>{!c?.assigned_to?<button className="primary" disabled={busy} onClick={()=>action('claim',{},'已接待')}>接待会话</button>:null}<button className="secondary" disabled={busy||c?.status==='closed'} onClick={()=>action('close',{},'会话已结束')}>结束会话</button></header>{notice?<p className="chat-note" role="status">{notice}</p>:null}{chat.error?<p className="chat-error">{chat.error}</p>:null}<Transcript messages={chat.messages} conversation={c} actor="agent" older={chat.older} loadOlder={chat.loadOlder} onBottom={setBottom}/><div className="desk-quick"><button onClick={()=>setPrefill({value:'您好，我来为您处理。请关联需要咨询的订单，不要发送密码或完整卡密。',key:Date.now()})}>接待问候</button><button onClick={()=>setPrefill({value:'已经收到您的问题，我会核查订单情况，请稍等。',key:Date.now()})}>处理中</button><button onClick={()=>setPrefill({value:'如需后续跟进，我可以将本次问题转为工单。',key:Date.now()})}>售后跟进</button></div><Composer key={id} cid={id} actor="agent" send={chat.send} disabled={c?.assigned_to!==agent.id||c?.status==='closed'} prefill={prefill}/></section><aside className="desk-context"><h3>客户与订单</h3><small>联系邮箱不等同于订单归属证明</small><p className="desk-contact">{c?.contact_email||'暂未提供邮箱'}</p>{c?.order?<div className="chat-order-card"><strong>{c.order.product_name}</strong><small>{c.order.variant_name}</small><small>{c.order.id}</small><span>{money(c.order.total)} · {c.order.status==='paid'?'已付款':c.order.status==='pending'?'待付款':'已关闭'}</span></div>:<p>客户尚未关联订单。</p>}<p className="desk-muted">客服只查看订单摘要，不展示卡密，不提供改余额或付款状态操作。</p><h3>转接客服</h3><select aria-label="目标客服" value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择在线客服</option>{agents.filter(a=>a.id!==c?.assigned_to).map(a=><option key={a.id} value={a.id}>{a.display_name||a.id.slice(0,8)}</option>)}</select><button className="secondary" disabled={!target||busy||c?.status==='closed'} onClick={()=>action('transfer',{agent_id:target},'已转接')}>确认转接</button><h3>售后跟进</h3>{c?.ticket_id?<p>已关联工单：{c.ticket_id}</p>:<button className="secondary" disabled={!c?.order||c.order.status!=='paid'} onClick={()=>setTicket(!ticket)}>转为工单</button>}{ticket&&!c?.ticket_id?<form className="stack-form desk-ticket" onSubmit={convert}><label><span>工单标题</span><input name="title" required minLength={3} maxLength={100}/></label><label><span>问题摘要</span><textarea name="body" required minLength={10} maxLength={3000}/></label><select name="priority" aria-label="工单优先级"><option value="medium">中优先级</option><option value="low">低优先级</option><option value="high">高优先级</option></select><button className="primary" disabled={busy}>保存工单</button></form>:null}</aside></div>;
}
export default function SupportWorkbench(){
  const [agent,setAgent]=useState<Agent|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[status,setStatus]=useState('waiting'),[items,setItems]=useState<QueueItem[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[selected,setSelected]=useState<string|null>(null),[duty,setDuty]=useState(false),[version,setVersion]=useState(0);
  const agentIdentity=useRef('');
  const refresh=useCallback(()=>setVersion(v=>v+1),[]),exit=useCallback(()=>{setSelected(null);refresh();},[refresh]);
  useEffect(()=>{let alive=true;async function check(){try{const next=await api<Agent>('/support/agent/session');if(alive){if(agentIdentity.current&&agentIdentity.current!==next.id+next.role){setSelected(null);setDuty(false);}agentIdentity.current=next.id+next.role;setAgent(next);setError('');}}catch(e){if(alive){setAgent(null);setSelected(null);setDuty(false);setError(errorText(e));}}finally{if(alive)setReady(true);}}void check();const changed=()=>{setAgent(null);setSelected(null);setDuty(false);void check();};const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('piusgo-auth'):null;if(channel)channel.onmessage=e=>{if(e.data==='changed')changed();};window.addEventListener('piusgo-auth-changed',changed);const timer=setInterval(check,15000);return()=>{alive=false;channel?.close();clearInterval(timer);window.removeEventListener('piusgo-auth-changed',changed);};},[]);
  useEffect(()=>{if(!agent)return;let alive=true;async function load(){try{const data=await api<{items:QueueItem[];total:number}>(`/support/agent/conversations?status=${status}&page=${page}`);if(alive){setItems(data.items);setTotal(data.total);}}catch(e){if(alive){setError(errorText(e));if(e instanceof ApiError&&(e.status===401||e.status===403)){setAgent(null);setSelected(null);}}}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},5000);return()=>{alive=false;clearInterval(timer);};},[agent?.id,status,page,version]);
  useEffect(()=>{if(!agent||!duty)return;const heartbeat=()=>{if(!document.hidden)api('/support/agent/presence',{online:true}).catch(e=>setError(errorText(e)));};heartbeat();const timer=setInterval(heartbeat,20000);return()=>clearInterval(timer);},[agent?.id,duty]);
  async function toggle(){try{await api('/support/agent/presence',{online:!duty});setDuty(!duty);}catch(e){setError(errorText(e));}}
  async function choose(item:QueueItem){try{if(!item.assigned_to)await api(`/support/agent/conversations/${item.id}/claim`,{});setSelected(item.id);refresh();}catch(e){setError(errorText(e));}}
  if(!agent)return <main id="main" className="site-main"><section className="panel empty"><h1>客服工作台</h1><p>{ready?error:'正在验证客服权限…'}</p>{ready?<Link className="primary" href="/login?next=%2Fsupport">使用客服或管理员账号登录</Link>:null}</section></main>;
  return <main id="main" className="support-desk"><header className="desk-header"><div><span className="eyebrow">SUPPORT WORKSPACE</span><h1>客服工作台</h1></div><span>{agent.name}</span><button className={duty?'primary':'secondary'} onClick={toggle}>{duty?'接待中 · 暂停接待':'开始接待'}</button><Link href={agent.role==='admin'?'/admin':'/account'}>返回{agent.role==='admin'?'管理后台':'个人中心'}</Link></header>{agent.role==='admin'?<FAQEditor/>:null}{error?<p className="chat-error" role="alert">{error}</p>:null}<div className="desk-layout"><aside className="desk-queue"><div className="desk-tabs">{[['waiting','待接待'],['active','处理中'],['closed','已结束']].map(([v,t])=><button className={status===v?'active':''} key={v} onClick={()=>{setStatus(v);setPage(1);}}>{t}</button>)}</div>{items.map(item=><button className={`desk-queue-item ${selected===item.id?'selected':''}`} key={item.id} onClick={()=>void choose(item)}><b>客户会话 {item.id.slice(-6)}</b><small>{new Date(item.updated*1000).toLocaleString('zh-CN')}</small>{item.unread>0?<em>{item.unread}</em>:null}</button>)}{!items.length?<p className="desk-empty">暂无会话</p>:null}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(total/20))}</span><button disabled={page>=Math.ceil(total/20)} onClick={()=>setPage(p=>p+1)}>下一页</button></div></aside>{selected?<DeskThread key={selected+agent.id} id={selected} agent={agent} exit={exit} refresh={refresh}/>:<section className="desk-placeholder"><h2>选择一个会话开始处理</h2><p>消息保存在服务器，可在断线后继续接待。</p></section>}</div></main>;
}
