"""initial PostgreSQL schema
Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('answer', sa.String(length=64), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_challenge_attempts'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_index('ix_challenges_expires', 'challenges', ['expires'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('badge', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.CheckConstraint('price >= 0 AND stock >= 0', name='ck_product_values'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('rates',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_rates'))
    )
    op.create_index('ix_rates_expires', 'rates', ['expires'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_users_balance'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_user_created', 'audit_events', ['user_id', 'created'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('minimum', sa.BigInteger(), nullable=False),
    sa.Column('used', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('amount >= 0 AND minimum >= 0 AND used IN (0,1)', name='ck_coupon_values'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupons_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('id', 'user_id', name='uq_coupon_owner'),
    sa.UniqueConstraint('user_id', 'kind', name=op.f('uq_coupons_user_id'))
    )
    op.create_table('ledger',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('bonus', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.CheckConstraint('amount > 0 AND bonus >= 0', name='ck_ledger_values'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger')),
    sa.UniqueConstraint('user_id', 'request_key', name=op.f('uq_ledger_user_id'))
    )
    op.create_index('ix_ledger_user_created', 'ledger', ['user_id', 'created'], unique=False)
    op.create_table('lottery',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('campaign', sa.String(length=30), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.CheckConstraint('won IN (0,1)', name='ck_lottery_result'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lottery_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'campaign', name=op.f('pk_lottery'))
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_expires', 'sessions', ['expires'], unique=False)
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= 0 AND stock >= 0', name='ck_variant_values'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants')),
    sa.UniqueConstraint('id', 'product_id', name='uq_variant_product')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=191), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('discount', sa.BigInteger(), nullable=False),
    sa.Column('coupon_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivery', sa.Text(), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('variant_id', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.CheckConstraint("payment_method IN ('mock','alipay','wechat','balance')", name='ck_order_payment'),
    sa.CheckConstraint("status IN ('pending','paid','cancelled')", name='ck_order_status'),
    sa.CheckConstraint('quantity BETWEEN 1 AND 10 AND total >= 0 AND discount >= 0', name='ck_order_values'),
    sa.ForeignKeyConstraint(['coupon_id', 'user_id'], ['coupons.id', 'coupons.user_id'], name='fk_order_coupon_owner'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['variants.id', 'variants.product_id'], name='fk_order_variant_product'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('id', 'user_id', name='uq_order_owner'),
    sa.UniqueConstraint('user_id', 'request_key', name=op.f('uq_orders_user_id'))
    )
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id', 'user_id'], ['orders.id', 'orders.user_id'], name='fk_ticket_order_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index('ix_tickets_user_created', 'tickets', ['user_id', 'created'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_user_created', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('variants')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_index('ix_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('lottery')
    op.drop_index('ix_ledger_user_created', table_name='ledger')
    op.drop_table('ledger')
    op.drop_table('coupons')
    op.drop_index('ix_audit_events_user_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_index('ix_rates_expires', table_name='rates')
    op.drop_table('rates')
    op.drop_table('products')
    op.drop_index('ix_challenges_expires', table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
