"""guest checkout mail outbox and ticket priority
Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_outbox',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=191), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt', sa.Float(), nullable=False),
    sa.Column('locked_at', sa.Float(), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('sent_at', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('queued','sending','sent','mock_delivered','failed')", name='ck_mail_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_mail_outbox_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_outbox')),
    sa.UniqueConstraint('order_id', name=op.f('uq_mail_outbox_order_id'))
    )
    op.create_index('ix_mail_status_next', 'mail_outbox', ['status', 'next_attempt'], unique=False)
    op.alter_column('audit_events', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('orders', sa.Column('guest_key', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.Float(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index('ix_guest_orders_created', 'orders', ['guest_key', 'created'], unique=False)
    op.create_unique_constraint('uq_guest_order_request', 'orders', ['guest_key', 'request_key'])
    op.create_unique_constraint('uq_order_guest_owner', 'orders', ['id', 'guest_key'])
    op.add_column('tickets', sa.Column('guest_key', sa.String(length=64), nullable=True))
    op.add_column('tickets', sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False))
    op.alter_column('tickets', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index('ix_guest_tickets_created', 'tickets', ['guest_key', 'created'], unique=False)
    op.create_unique_constraint('uq_ticket_order', 'tickets', ['order_id'])
    op.create_foreign_key(op.f('fk_tickets_order_id_orders'), 'tickets', 'orders', ['order_id'], ['id'])
    op.create_check_constraint('ck_order_owner_kind','orders','(user_id IS NOT NULL) <> (guest_key IS NOT NULL)')
    op.create_check_constraint('ck_ticket_owner_kind','tickets','(user_id IS NOT NULL) <> (guest_key IS NOT NULL)')
    op.create_check_constraint('ck_ticket_priority','tickets',"priority IN ('low','medium','high')")
    # ### end Alembic commands ###

def downgrade():
    if op.get_bind().execute(sa.text("SELECT EXISTS(SELECT 1 FROM orders WHERE user_id IS NULL) OR EXISTS(SELECT 1 FROM mail_outbox)")).scalar():
        raise RuntimeError("Refusing downgrade with guest orders or delivery mail; migrate data first")
    op.drop_constraint('ck_ticket_priority','tickets',type_='check')
    op.drop_constraint('ck_ticket_owner_kind','tickets',type_='check')
    op.drop_constraint('ck_order_owner_kind','orders',type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tickets_order_id_orders'), 'tickets', type_='foreignkey')
    op.drop_constraint('uq_ticket_order', 'tickets', type_='unique')
    op.drop_index('ix_guest_tickets_created', table_name='tickets')
    op.alter_column('tickets', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'guest_key')
    op.drop_constraint('uq_order_guest_owner', 'orders', type_='unique')
    op.drop_constraint('uq_guest_order_request', 'orders', type_='unique')
    op.drop_index('ix_guest_orders_created', table_name='orders')
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'guest_key')
    op.alter_column('audit_events', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index('ix_mail_status_next', table_name='mail_outbox')
    op.drop_table('mail_outbox')
    # ### end Alembic commands ###
