"""member profile login history and recharge method
Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger', sa.Column('payment_method', sa.String(length=20), server_default='mock', nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=40), server_default='', nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=24), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('previous_login_at', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('previous_login_ip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'previous_login_ip')
    op.drop_column('users', 'previous_login_at')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'display_name')
    op.drop_column('ledger', 'payment_method')
    # ### end Alembic commands ###
