"""secure customer support conversations
Revision ID: 0007
Revises: 0006
"""
from alembic import op
import sqlalchemy as sa

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None

def upgrade():
    op.drop_constraint('ck_users_role','users',type_='check')
    op.create_check_constraint('ck_users_role','users',"role IN ('member','admin','support')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_faqs'))
    )
    op.create_table('support_streams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reader_key', sa.String(length=80), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_streams'))
    )
    op.create_index('ix_support_stream_expiry', 'support_streams', ['expires'], unique=False)
    op.create_table('support_presence',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_presence_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_support_presence'))
    )
    op.create_table('support_conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('guest_key', sa.String(length=64), nullable=True),
    sa.Column('assigned_to', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='waiting', nullable=False),
    sa.Column('contact_email', sa.String(length=191), server_default='', nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('last_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('updated', sa.Float(), nullable=False),
    sa.CheckConstraint("status IN ('waiting','active','closed')", name='ck_support_status'),
    sa.CheckConstraint('(user_id IS NOT NULL) <> (guest_key IS NOT NULL)', name='ck_support_owner'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_support_conversations_assigned_to_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_support_conversations_order_id_orders')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_support_conversations_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_conversations')),
    sa.UniqueConstraint('guest_key', name='uq_support_guest'),
    sa.UniqueConstraint('user_id', name='uq_support_member')
    )
    op.create_index('ix_support_assignment', 'support_conversations', ['assigned_to', 'updated'], unique=False)
    op.create_index('ix_support_queue', 'support_conversations', ['status', 'updated'], unique=False)
    op.create_table('support_attachments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('sender_key', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.CheckConstraint('size > 0 AND size <= 2000000', name='ck_support_attachment_size'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], name=op.f('fk_support_attachments_conversation_id_support_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_attachments')),
    sa.UniqueConstraint('id', 'conversation_id', name='uq_support_attachment_conversation')
    )
    op.create_table('support_reads',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('reader_key', sa.String(length=80), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.CheckConstraint('last_seq >= 0', name='ck_support_read_seq'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], name=op.f('fk_support_reads_conversation_id_support_conversations')),
    sa.PrimaryKeyConstraint('conversation_id', 'reader_key', name=op.f('pk_support_reads'))
    )
    op.create_table('support_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('sender_key', sa.String(length=80), nullable=False),
    sa.Column('sender_role', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('attachment_id', sa.String(length=32), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.CheckConstraint("sender_role IN ('customer','agent')", name='ck_support_sender'),
    sa.CheckConstraint('seq > 0', name='ck_support_message_seq'),
    sa.ForeignKeyConstraint(['attachment_id', 'conversation_id'], ['support_attachments.id', 'support_attachments.conversation_id'], name='fk_support_message_attachment'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], name=op.f('fk_support_messages_conversation_id_support_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages')),
    sa.UniqueConstraint('attachment_id', name='uq_support_attachment_message'),
    sa.UniqueConstraint('conversation_id', 'sender_key', 'client_id', name='uq_support_message_idempotency'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_support_message_seq')
    )
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Support history must be retained; restore an explicitly selected backup for rollback')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_messages')
    op.drop_table('support_reads')
    op.drop_table('support_attachments')
    op.drop_index('ix_support_queue', table_name='support_conversations')
    op.drop_index('ix_support_assignment', table_name='support_conversations')
    op.drop_table('support_conversations')
    op.drop_table('support_presence')
    op.drop_index('ix_support_stream_expiry', table_name='support_streams')
    op.drop_table('support_streams')
    op.drop_table('support_faqs')
    # ### end Alembic commands ###
